---
title: "climatology"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/slewa/Projects/heat_stress")

library(tidyverse)
library(dygraphs)
library(xts)
library(timetk)
library(zoo)
library(forecast)
library(fable)
library(sweep)
library(viridis)
library(lubridate)
library(scales)
```


```{r}
nldas_wide <- read_rds("data/nldas_wide.rds")

# Add one second to duplicate times
local_dst_adjust <-
  nldas_wide %>%
    mutate(row = dplyr::row_number()) %>% 
    tsibble::duplicates(key = installation, index = local_dttm) %>% 
    filter(local_dttm != lead(local_dttm, default = "1")) %>% 
    mutate(local_dttm = local_dttm + seconds(1))

local_dst_adjust

# Remove rows with duplicate local times and replace with updated rows (+1 second)

nldas_wide <-
  nldas_wide %>%
    mutate(row = dplyr::row_number()) %>% 
    filter(!row %in% local_dst_adjust$row) %>% 
    bind_rows(local_dst_adjust) %>% 
    arrange(local_dttm) %>% 
    dplyr::select(-row) %>% 
    dplyr::select(installation, local_dttm, tmp_f, heat_index, wbgt_f) 

```



## Construct climatology (1990-2018)

```{r}
#Construct climatology (1990-2018)

nldas_wide <-
  nldas_wide %>% 
  filter(lubridate::year(local_dttm) < 2019 &
           lubridate::year(local_dttm) > 1989) %>%
    mutate(month = month(local_dttm), 
           day = day(local_dttm)) 

nldas_wide

nest_nldas <-
  nldas_wide %>% 
    nest(., data = local_dttm:day)

nest_nldas

nest_nldas %>% slice(1) %>% unnest(data)



climatology_function <- function(df) {
  df %>% 
    group_by(month, day) %>% 
        summarise(mean_tmp = mean(tmp_f),
                  max_tmp = max(tmp_f),
                  min_tmp = min(tmp_f),
                  sd_tmp = sd(tmp_f),
                  tmp_95th = quantile(tmp_f, probs = 0.95),
                  mean_hi = mean(heat_index),
                  max_hi = max(heat_index),
                  min_hi = min(heat_index),
                  sd_hi = sd(heat_index),
                  hi_95th = quantile(heat_index, probs = 0.95),
                  mean_wbgt = mean(wbgt_f),
                  max_wbgt = max(wbgt_f),
                  min_wbgt = min(wbgt_f),
                  sd_wbgt = sd(wbgt_f),
                  wbgt_95th = quantile(wbgt_f, probs = 0.95) 
            ) %>% 
    unite(mon_day, month:day, sep = "-", remove = FALSE)
}


nldas_climatology <- 
  nest_nldas %>% 
    mutate(climatology = 
      map(nest_nldas$data, climatology_function))


nldas_climatology

nldas_climatology$climatology[[1]]
```

## Plot climatologies

### Single plot
```{r plot_climatology_single}


nldas_climatology$climatology[[1]] %>%
    ungroup() %>% 
    dplyr::select(-c(month, day, sd_tmp, sd_hi, sd_wbgt)) %>%
    mutate(mon_day = paste0("2019", "-", mon_day),
           mon_day = as.Date(mon_day)) %>% 
    gather(., key = "variable", value = "value", mean_tmp:wbgt_95th) %>% 
    na.omit(mon_day) %>%   # Feb 29 coded as NA "leap year"
    filter(variable == c("max_wbgt", "mean_wbgt", "min_wbgt", "wbgt_95th")) %>% 
    ggplot(aes(x = mon_day, y = value, color = variable)) + 
    geom_smooth(alpha = 0.1) +
    geom_point() +
    scale_x_date(labels = date_format("%b-%d"),
               breaks = date_breaks("months")) +
    labs(
      title = "Eglin AFB WBGT Climatology",
      x = "Month-Day of Year",
      y = "WBGT (°F)"
    ) +
    theme(legend.position = "bottom") +
    theme_bw()
  


```


### All plots

```{r plot_climatologies_map}

# Plot function
climatology_plot <- function(df) {
  df %>%
    ungroup() %>% 
    dplyr::select(-c(month, day, sd_tmp, sd_hi, sd_wbgt)) %>%
    mutate(mon_day = paste0("2019", "-", mon_day),
           mon_day = as.Date(mon_day)) %>% 
    gather(., key = "variable", value = "value", mean_tmp:wbgt_95th) %>% 
    na.omit(mon_day) %>%   # Feb 29 coded as NA "leap year"
    filter(variable == c("max_wbgt", "mean_wbgt", "min_wbgt", "wbgt_95th")) %>% 
    ggplot(aes(x = mon_day, y = value, color = variable)) + 
    geom_smooth(alpha = 0.1) +
    geom_point() +
    scale_x_date(labels = date_format("%b-%d"),
               breaks = date_breaks("months")) +
    labs(
      title = "WBGT Climatology",
      x = "Month-Day of Year",
      y = "WBGT (°F)"
    ) +
    theme(legend.position = "bottom") +
    theme_bw()
}

# Map plot function over list

names(nldas_climatology$climatology) <- nldas_climatology$installation
  

map(nldas_climatology$climatology, climatology_plot)


```

