---
title: "Heat Stress Research"
output:
  html_document:
    toc: true
    toc_float: true
---

Welcome to our heat stress research website!  

**Stephen Lewandowski**  
**Advisor: Jeffrey Shaman**  

Columbia University Mailman School of Public Health  
Environmental Health Sciences  
[Climate and Health Program](https://www.mailman.columbia.edu/research/climate-and-health-program)


## Introduction  

### Background
Project Title: Modeling Environmental Impacts on Heat Stress Illnesses among DoD Servicemembers  

Heat stress illnesses (HSIs), including heat stroke and heat exhaustion, pose a serious and potentially fatal health threat to US forces. HSI incidence rates display an increasing trend (cases among active duty U.S. Army servicemembers increased every year from 2014 to 2017). This project seeks to develop tools to better understand the impact of heat events on HSI cases across different installations. 

The objective of this  investigation is to develop installation-specific operational models for prevention and control of HSIs. This investigation will apply modern epidemiology methods with high-resolution gridded meteorology data to describe the association between heat exposure and heat stress illnesses (HSI) in active duty service members exposed to ambient heat. We will assess absolute and relative values of multiple indices of environmental heat, including heat index (HI) and wet bulb globe temperature (WBGT), to identify trends and define relevant windows of exposure, potential action-level thresholds, and time-in-season effects.  We will characterize individual risk factors as effect modifiers, including sex, age, grade/rank, and body mass index (BMI).  


### Specific Aims  
1. Develop exposure-response curves for environmental heat and HSI morbidity to understand the association between heat and HSIs in the U.S. military at installation, regional, and national levels. We will assess the relationship between environmental heat indicators (temperature, wet bulb globe temperature (WBGT), and heat index) and HSIs. We will investigate relevant windows of exposure through lag analyses, identify breakpoint thresholds, assess time-in-season effects, and determine whether WBGT estimated from meteorological measures explains variability in HSIs better than temperature or heat index. This aim will produce multi-level exposure-response curves for heat indicators and lag structures. We hypothesize that response and lag effects will be nonlinear and that response thresholds will vary by installation due to population dynamics, seasonality, climate features, and acclimatization.  

2. Characterize the contribution of individual risk factors on HSIs. We will assess potential individual effect modifiers, including sex, age group, race/ethnicity, military rank group, and body mass index (BMI, upon entry into service), in terms of odds ratios. We hypothesize that the impact of the risk factors will not vary by location, and that sex/gender, age, and BMI will modify the effect of heat on HSI occurrences. 

3. Predict the impact of future climate change and changes in risk factor distributions on HSI cases at major DoD training installations in CONUS.

### Research Questions

Are recent increases in HSI incidence attributal to changes in ambient temperature/heat? Does this relationship vary by location? How much of the variance in HSIs is accounted for by the environmental conditions?  

Which indices of heat best predict HSI outcomes over short-term and annual time periods -- temperature, heat index, or WBGT? Does this vary by geographic/climate region?  

Do we observe effect estimate changes at defined Heat Category boundaries? Are the universal WBGT-based Heat Cat designations appropriate for all installations?  



## Data Preparation

### NLDAS-2 Weather Data Preparation
- Examine location shapefiles and NLDAS-2 grid overlays [[here]](shapefiles.html)  

- Instructions to download NLDAS-2 files using `wget` command [[here]](nldas_wget.html)  

- Extract locations (cells) and variables from NLDAS-2 .nc4 files with conversion to raster brick [[here]](extract_cells.html)  

- Link NLDAS estimates assembled in `extract_cells`to specific locations and summarizes the data [[here]](installation_nldas.html)

- Add unit conversions, calculate new variables, and add Heat Index and WBGT indices [[here]](nldas_indices.html)

### Heat Stress Illness Data Preparation
- Functions to read and compile Defense Medical Epidemiology Database (DMED) queries [[here]](dmed_read.html)

## Climate 

- Time series formats for NLDAS-2 data (zoo, xts, ts) [[here]](nldas_timeseries.html)

- Fable/tsibble time series format for NLDAS-2 data [[here]](nldas_fable.html)

- Aggregate over calendar periods [[here]](nldas_averaged.html) 

- Climatologies (1990-2018) [[here]](climatology.html) 

- Annual temperature and heat indices [[here]](annual_tables.html)

- Air Force weather station data (U.S. Army installations, 2008-2018) - sensitivity analysis [[here]](af_weather.html)

## Heat Stress Outcomes

- DMED Summary (annual) [[here]](dmed_summary.html)  

## Models

- DMED Models (annual, out-patient) [[here]](dmed_models.html)

- DMED Models (annual, in-patient) [[here]](dmed_models_hospitalization.html)

- Mixed Models (exploratory) [[here]](mixed_models.html)

- Mixed Models - Poisson  [[here]](mixed_poisson.html)

- Overview of daily models [[here]](daily_models.html) 

- Case-crossover Models (daily) [[here]](case_crossover.html)
