---
title: "nldas_exploratory"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/slewa/Projects/heat_stress")

library(tidyverse)
library(dygraphs)
library(xts)
library(timetk)
library(zoo)
```


```{r}
nldas_nest <- read_rds("data/nldas_nest.rds")
nldas_nest
```




https://cran.rstudio.com/web/packages/sweep/vignettes/SW01_Forecasting_Time_Series_Groups.html

```{r make_ts, warning = FALSE}


# Function to convert hourly `dttm` to a time series (zoo) object

make_ts = function(df) {
  zoo::zoo(x = df[["value"]],
           order.by = df[["local_dttm"]],
           frequency = 24)
}


make_xts = function(df) {
  timetk::tk_xts(
            data = df,
            select =  df[["value"]],
            date_var = df[["local_dttm"]])
}



make_ts(nldas_nest$data[[1]]) %>% class()  dygraph() 



TMP_xts <-
  nldas_nest %>% 
    filter(variable == "TMP") %>%
    mutate(data_ts = 
      purrr::map(data, timetk::tk_xts))



TMP_ts <-
  nldas_nest %>% 
    filter(variable == "TMP") %>%
    mutate(data_ts = 
      purrr::map(data, make_ts))

TMP_ts

TMP_ts$data_ts %>% [[1]]


dygraph(TMP_ts[1,]$data_ts)





map(TMP_ts$data_ts, ~dygraph(.))



TMP_ts


```

